#!/bin/bash

# https://github.com/rjsears/chia_plot_manager/blob/7ad9b4790a8322e24cac4763d8707e8fd0c3eb30/extras/set_cpu_to_performance.sh
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
for d in /sys/devices/system/cpu/cpu*/cpufreq; do
    echo "performance" > $d/scaling_governor
    #echo "1200000" > $d/scaling_min_freq
done
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

mkdir -p /var/lib/prometheus/node-exporter
chown chia.chia /var/lib/prometheus/node-exporter
#prometheus-node-exporter --collector.textfile.directory="/tmp/metrics"
