#!/bin/bash

set -euvx

HERE=$(realpath "${BASH_SOURCE%/*}")
SITES="${HERE}/sites/"
BACK40="${HERE}/back40/"
YARDS="${HERE}/yards/"
PORCHES="${HERE}/porches/"
WAGONS="${HERE}/wagons/"

mkdir --parents "${SITES}/"{001..45} "${BACK40}/"{001..45} "${WAGONS}/"{800..806} "${YARDS}/"{900..909} "${PORCHES}/"{700..701}
