#!/bin/bash

set -euvx

HERE=$(realpath "${BASH_SOURCE%/*}")
SITES="${HERE}/sites/"
YARDS="${HERE}/yards/"
WAGONS="${HERE}/wagons/"

mkdir --parents "${SITES}/"{001..21} "${WAGONS}/"{800..806} "${YARDS}/"{900..907}
