{
 "title": "Full Node",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "used (ram)"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "total (ram)" },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "used (swap)"
    },
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "total (swap)" },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) + (node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "used (all)"
    },
    {
     "expr": "node_memory_MemTotal_bytes + node_memory_SwapTotal_bytes",
     "legendFormat": "total (all)"
    }
   ]
  },
  {
   "title": "memory - probably not good",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "used (ram)"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "total (ram)" },
    {
     "expr": "(node_memory_MemTotal_bytes + node_memory_SwapTotal_bytes) - (node_memory_MemAvailable_bytes + node_memory_SwapFree_bytes)",
     "legendFormat": "used (all)"
    },
    {
     "expr": "node_memory_MemTotal_bytes + node_memory_SwapTotal_bytes",
     "legendFormat": "total (all)"
    }
   ]
  },
  {
   "title": "node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "chia_full_node_node_height", "legendFormat": "height" },
    {
     "expr": "((chia_full_node_node_synced == bool 0 and on () (chia_full_node_node_synced == 0)) * 0.8) + 0.6",
     "legendFormat": "not synced"
    },
    {
     "expr": "rate(chia_full_node_total_signage_points and on () (chia_full_node_node_synced == 1)[5m:]) * (18.75) / 2",
     "legendFormat": "signage points"
    },
    {
     "expr": "rate(chia_full_node_node_height and on () (chia_full_node_node_synced == 1)[10m:]) * 18.75",
     "legendFormat": "blocks"
    },
    {
     "expr": "(absent(vector(1.1) and on () (increase(node_time_seconds[30s]) > 0)) * 0.8) + 0.6",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chia_full_node_connection_count",
     "legendFormat": "{{node_type}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "3 * avg (irate(node_cpu_seconds_total{mode=~'(user|nice|system)'}[1m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "3 * avg (rate(node_cpu_seconds_total{mode=~'(user|nice|system)'}[15m]))",
     "legendFormat": "usage (filtered)"
    },
    { "expr": "node_load1", "legendFormat": "load average (1m)" }
   ]
  },
  {
   "title": "balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "chia_wallet_confirmed_balance{wallet_id=\"1\"} / 1000000000000",
     "legendFormat": "xch"
    },
    {
     "expr": "chia_wallet_unspent_coin_count{wallet_id=\"1\"}",
     "legendFormat": "coins"
    }
   ]
  },
  {
   "title": "cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "chia_full_node_block_cost / chia_full_node_block_max_cost",
     "legendFormat": "block"
    },
    {
     "expr": "chia_full_node_mempool_cost / chia_full_node_mempool_max_total_cost",
     "legendFormat": "mempool"
    }
   ]
  },
  {
   "title": "disks",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value",
     "legendFormat": "temp - {{disk}}"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "disks - individual",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"mmcblk0\"}[1m])",
     "legendFormat": "system"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sda\"}[1m])",
     "legendFormat": "chia"
    }
   ]
  }
 ]
}