#!/bin/bash

#set -vx

farm=/farm
sites=${farm}/sites
wagons=${farm}/wagons
yards=${farm}/yards

#date --iso-8601=seconds

all_mounts=$(echo "${sites}"/* "${wagons}"/* "${yards}"/*)

df -h ${all_mounts}

function heading() {
    printf "\n  ====\n"
}

heading

for mount in ${all_mounts}; do
    drive=$(findmnt --noheadings --output SOURCE "${mount}")
    echo "    ---- ${drive} -> ${mount}"
    sudo smartctl -a "${drive}" | grep -E '(Start_Stop_Count|Spin_Retry_Count)'
done

heading

top -b -n 1 | grep -E '(load average|PID USER|chia$)'

heading

#chia netspace

chia farm summary | grep -v 'Note: log into your'

heading

chia wallet show

heading

for log in $(ls "${farm}"/logs/*.log | tail -n 5); do
    if [[ -f "${log}" ]]; then
        echo "    ---- ${log}"
        grep -E "(Time for phase|Starting phase 1|Total time)" "${log}"
    fi
done
