#!/bin/bash

#set -vx

farm=/farm
sites=${farm}/sites
wagons=${farm}/wagons
yards=${farm}/yards

#date --iso-8601=seconds

function heading() {
    printf "\n  ====\n"
}

all_mounts=$(echo "${sites}"/* "${wagons}"/* "${yards}"/*)

pr --merge --omit-header --width 100 <(chia farm summary | grep -v 'Note: log into your') <(chia wallet show) | grep --color=always -e '^' -e 'Block rewards: [^ ]*'

heading

grep --no-filename --recursive -E '(error|plots were eligible for farming .* Time: [^0])' ~/.chia/mainnet/log/

heading

df -h ${all_mounts} | grep -v ' /$' | grep --color=always -P '(^|(99|100)%(?= /farm/[wy]))'

heading

for mount in ${all_mounts}; do
    partition=$(findmnt --noheadings --output SOURCE "${mount}")

    if [[ "${partition}" ]]; then
        echo "    ---- ${partition} -> ${mount}"

        # https://unix.stackexchange.com/a/226426
        part=$(basename ${partition})
        disk=$(readlink /sys/class/block/$part)
        disk=${disk%/*}
        disk=/dev/${disk##*/}

        sudo smartctl -a "${disk}" | grep -E '(Start_Stop_Count|Spin_Retry_Count)'
    fi
done

heading

free --human

heading

top -b -c -n 1 -p $(pgrep -d',' -f 'chia plots create') | grep -E '(load average|PID USER|chia)'

heading

for log in $(ls "${farm}"/logs/*.log | tail -n 10 | sort --reverse); do
    if [[ -f "${log}" ]]; then
        echo "    ---- ${log}"
        grep -E "(Time for phase|Starting phase 1|Total time)" "${log}"
    fi
done
