#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "$0")"; pwd)

SYSTEMD_DIR=/usr/local/lib/systemd/system

mkdir -p "${SYSTEMD_DIR}"
#for SERVICE in $(ls "${SCRIPT_DIR}"/*.{service,target})
for EXTENSION in service mount
do
    for SERVICE in $(ls "${SCRIPT_DIR}"/*.${EXTENSION})
    do
        ln -s "${SERVICE}" "${SYSTEMD_DIR}"
        systemctl enable "${SERVICE}"
    done
done
